# Generated by Django 4.1 on 2022-09-01 08:33

import carousel.services
import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carousel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slide",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="slide",
            name="cover",
            field=models.FileField(
                default="",
                upload_to=carousel.services.upload_slide_path,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["png", "webp", "mp4", "mpv"]),
                    config.validators.file_size,
                ],
            ),
        ),
    ]
