# Generated by Django 4.1 on 2022-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carousel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carousel",
            name="image",
        ),
        migrations.AddField(
            model_name="carousel",
            name="thumbnail",
            field=models.ImageField(default="", upload_to="carousel"),
        ),
    ]
