# Generated by Django 4.1 on 2022-09-06 15:44

import carousel.services
import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carousel", "0002_remove_slide_thumbnail_slide_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="cover",
            field=models.FileField(
                default="",
                upload_to=carousel.services.upload_slide_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "webp", "jpg", "jpeg", "mp4", "mpv"]
                    ),
                    config.validators.file_size,
                ],
            ),
        ),
    ]
