# Generated by Django 4.1.2 on 2022-11-25 16:48

import config.validators
from django.db import migrations, models
import specifications.services


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Specification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "image",
                    models.ImageField(
                        upload_to=specifications.services.upload_image_path,
                        validators=[config.validators.validate_file_size],
                    ),
                ),
            ],
            options={
                "verbose_name": "specification",
                "verbose_name_plural": "specifications",
                "db_table": "specification",
            },
        ),
    ]
