# Generated by Django 4.1.2 on 2023-01-04 17:14

import config.validators
from django.db import migrations, models
import specifications.services


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0002_alter_specification_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specification",
            name="image",
            field=models.ImageField(
                upload_to=specifications.services.upload_image_path, validators=[config.validators.FileSizeValidator(2)]
            ),
        ),
    ]
