# Generated by Django 4.1 on 2022-09-07 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_alter_customuser_is_active_alter_customuser_is_staff"),
        ("products", "0007_media_is_cover_alter_media_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "basket",
            },
        ),
        migrations.CreateModel(
            name="BasketProducts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.PositiveIntegerField()),
                ("basket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="baskets.basket")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
            options={
                "db_table": "basket_products",
            },
        ),
        migrations.AddField(
            model_name="basket",
            name="products",
            field=models.ManyToManyField(through="baskets.BasketProducts", to="products.product"),
        ),
    ]
