# Generated by Django 4.1.2 on 2022-11-30 16:30

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0014_alter_productsspecifications_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=255, verbose_name="full_name")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name="phone"),
                ),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
            options={
                "db_table": "order",
            },
        ),
    ]
