# Generated by Django 4.1.2 on 2022-12-29 14:01

from django.db import migrations, models
import orders.enums


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_order_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.IntegerField(choices=[(1, "NEW"), (2, "PAID")], default=orders.enums.Status["NEW"]),
        ),
    ]
