# Generated by Django 4.1.2 on 2022-11-21 13:07

from django.db import migrations, models
import works.services


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to=works.services.upload_image_path, verbose_name="image")),
            ],
            options={
                "verbose_name": "work",
                "verbose_name_plural": "works",
                "db_table": "work",
            },
        ),
    ]
