# Generated by Django 4.1.2 on 2022-12-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="name",
            field=models.CharField(default="", max_length=100, verbose_name="name"),
        ),
    ]
