# Generated by Django 4.1 on 2022-08-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_media_path_alter_media_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["position"], "verbose_name": "product", "verbose_name_plural": "products"},
        ),
        migrations.AddField(
            model_name="product",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="position"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(verbose_name="price"),
        ),
    ]
