# Generated by Django 4.1 on 2022-09-01 08:33

import django.core.validators
from django.db import migrations, models

import products.services


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_options_product_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="path",
            field=models.FileField(
                upload_to=products.services.upload_media_path,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["png", "webp", "mp4", "mpv"]),
                ],
                verbose_name="path",
            ),
        ),
    ]
