# Generated by Django 4.1.2 on 2022-11-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_images_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.TextField(default="", verbose_name="short_description"),
        ),
    ]
