# Generated by Django 4.1.2 on 2022-11-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0001_initial"),
        ("products", "0011_alter_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductsSpecifications",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=255, verbose_name="value")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
                (
                    "specification",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="specifications.specification"),
                ),
            ],
            options={
                "db_table": "products_specifications",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.ManyToManyField(through="products.ProductsSpecifications", to="specifications.specification"),
        ),
    ]
