# Generated by Django 4.1.2 on 2022-11-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("specifications", "0001_initial"),
        ("products", "0012_productsspecifications_product_specifications"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsspecifications",
            options={"verbose_name": "product specifications", "verbose_name_plural": "product specifications"},
        ),
        migrations.AlterUniqueTogether(
            name="productsspecifications",
            unique_together={("product", "specification")},
        ),
    ]
