# Generated by Django 4.1.2 on 2022-11-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_productsspecifications_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsspecifications",
            options={
                "ordering": ["position"],
                "verbose_name": "product specifications",
                "verbose_name_plural": "product specifications",
            },
        ),
        migrations.AddField(
            model_name="productsspecifications",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="position"),
        ),
    ]
