# Generated by Django 4.1.2 on 2023-01-04 13:29

from django.db import migrations, models
import products.services


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_alter_productimage_image_productvideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.FileField(
                upload_to=products.services.upload_media_path,
                verbose_name="video",
            ),
        ),
    ]
