# Generated by Django 4.1.2 on 2023-01-04 17:14

import config.validators
import django.core.validators
from django.db import migrations, models
import products.services


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_alter_productvideo_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="",
                upload_to=products.services.upload_media_path,
                validators=[config.validators.FileSizeValidator(2)],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=products.services.upload_media_path,
                validators=[config.validators.FileSizeValidator(2)],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.FileField(
                upload_to=products.services.upload_media_path,
                validators=[
                    config.validators.FileSizeValidator(10),
                    django.core.validators.FileExtensionValidator(allowed_extensions=("avi", "mp4")),
                ],
                verbose_name="video",
            ),
        ),
    ]
